---
driver:
  name: vagrant

provisioner:
  name: ansible_push
  playbook: main.yml
  remote_user: vagrant
  host_key_checking: false
  chef_bootstrap_url: false
  verbose: "vv"

platforms:
  - name: ubuntu-14.04
  - name: centos-6.6
  - name: centos-7.2

suites: 
  - name: default
