---
- hosts: all
  serial: 1 # Preserve ordering
  tasks:
    - name: Install libselinux-python on centos
      yum:
        name: libselinux-python
      when: ansible_distribution == "CentOS"
      sudo: true
    - name: Remove private search domains from /etc/resolv.conf
      lineinfile:
        dest: /etc/resolv.conf
        state: absent
        regexp: ".*search.*"
      sudo: true

    - name: Running Ansible Setup
      setup:
      register: all_facts
      sudo: true

    - set_fact:
        distro: "{{ansible_lsb.description}}"
      when: ansible_lsb.description is defined
    - set_fact:
        distro: "{{ansible_distribution}} {{ansible_distribution_major_version}}"
      when: ansible_lsb.description is undefined

    - local_action: "shell echo '* [{{distro}}](#{{distro}})' >> README.md"

    - local_action: "shell echo '{{distro}}' >> .facts.md"
      when: ansible_lsb.description is defined
    - local_action: "shell echo '------------------------------------------------' >> .facts.md"
    - local_action: "shell echo '```json' >> .facts.md"
    - local_action: "shell echo '{{all_facts | to_json }}' | python -m json.tool >> .facts.md"
    - local_action: "shell echo '```\n\n' >> .facts.md"

